export const Scholarshipfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Vanier Canada Graduate Scholarships",
    profession: "Health Research",
    rating: "$50,000",
    reviews: 820,
    tags: ["Health Research", "Policy", "Science"],
    skill: "University of Toronto",
    price: 12000,
    location: "Post Graduate",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will assist with health research projects - Health Researcher",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Banting Postdoctoral Fellowships",
    profession: "Data Science",
    rating: "$70,000",
    reviews: 450,
    tags: ["Machine Learning", "AI", "Data Analytics"],
    skill: "University of British Columbia",
    price: 18000,
    location: "Post Graduate",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide data analysis and AI solutions - Data Scientist",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "NSERC Postgraduate Scholarships",
    profession: "Engineering",
    rating: "$30,000",
    reviews: 320,
    tags: ["Engineering", "Research", "Technology"],
    skill: "McGill University",
    price: 25000,
    location: "Doctorate",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will assist with engineering research - Engineering Consultant",
  },
];

export const ScholarshipUKfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Canadian Graduate Scholarships",
    profession: "Environmental Science",
    rating: "$35,000",
    reviews: 610,
    tags: ["Sustainability", "Climate Change", "Policy"],
    skill: "University of Alberta",
    price: 15000,
    location: "Post Graduate",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will consult on environmental sustainability - Environmental Scientist",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Trudeau Foundation Scholarships",
    profession: "Social Sciences",
    rating: "$40,000",
    reviews: 500,
    tags: ["Leadership", "Public Policy", "Social Justice"],
    skill: "Université de Montréal",
    price: 20000,
    location: "Post Graduate",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide insights on social policy and leadership - Policy Analyst",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Loran Scholars Foundation",
    profession: "Public Policy",
    rating: "$45,000",
    reviews: 410,
    tags: ["Leadership", "Public Policy", "Community Development"],
    skill: "Queen's University",
    price: 22000,
    location: "Undergraduate",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will offer mentorship and guidance on public policy - Policy Mentor",
  },
];

export const Destinationfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Cost of Living Calculator for Canada",
    profession: "Financial Analyst",
    rating: "$70,000",
    reviews: 590,
    tags: ["Economics", "Finance", "Cost of Living"],
    skill: "York University",
    price: 20000,
    location: "Use this tool to estimate how much it could cost to live in Canada",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will calculate living costs and financial planning for Canadian cities - Financial Analyst",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Best Cities to Live in Canada",
    profession: "Urban Planner",
    rating: "$60,000",
    reviews: 480,
    tags: ["Urban Development", "Infrastructure", "Sustainability"],
    skill: "University of Calgary",
    price: 17000,
    location: "Explore the best cities to live in based on quality of life and cost in Canada",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide consultancy on urban living and city planning in Canada - Urban Planner",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Pre-Departure Checklist for Canada",
    profession: "Travel Consultant",
    rating: "$50,000",
    reviews: 320,
    tags: ["Travel", "Visa", "Immigration"],
    skill: "University of Ottawa",
    price: 15000,
    location: "Essential tips before moving to Canada",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will assist with travel planning and visa preparation for Canada - Travel Consultant",
  },
];
