export const Scholarshipfreelancer = [
    {
      id: 1,
      img: "/images/team/fl-1.png",
      name: "Curtin Merit Scholarship ",
      profession: "Nursing Assistant",
      rating: "10,00,000",
      reviews: 595,
      tags: ["Figma", "HTML5", "Sketch"],
      skill: "Curtin University",
      price: 10000,
      location: "Under Graduate",
      level: "new",
      language: "Turkish",
      sort: "best-seller",
      title: "I will be your Nursing Assistant - UX Designer",
    },
    {
      id: 2,
      img: "/images/team/fl-2.png",
      name: "Unimoni Student Star",
      profession: "University of Melbourne",
      rating: "20,00,000",
      reviews: 423,
      tags: ["Illustrator", "Photoshop", "InDesign"],
      skill: "University of Melbourne",
      price: 20000,
      location: "Post Graduate",
      level: "lavel-1",
      language: "English",
      sort: "recommended",
      title: "I will create amazing designs as a Graphic Designer - Illustrators",
    },
    {
      id: 3,
      img: "/images/team/fl-3.png",
      name: "Young Women Awards ",
      profession: "Cranfield University",
      rating: "5,00,000",
      reviews: 312,
      tags: ["HTML", "CSS", "JavaScript"],
      skill: "Cranfield University",
      price: 30000,
      location: "Doctorate",
      level: "lavel-2",
      language: "Italian",
      sort: "new-arrivals",
      title: "I will develop web solutions as a Web Developer - Web Developers",
    },
  ];

  export const ScholarshipUKfreelancer = [
    {
      id: 1,
      img: "/images/team/fl-1.png",
      name: "Curtin Merit Scholarship ",
      profession: "Nursing Assistant",
      rating: "10,00,000",
      reviews: 595,
      tags: ["Figma", "HTML5", "Sketch"],
      skill: "Curtin University",
      price: 10000,
      location: "Under Graduate",
      level: "new",
      language: "Turkish",
      sort: "best-seller",
      title: "I will be your Nursing Assistant - UX Designer",
    },
    {
      id: 2,
      img: "/images/team/fl-2.png",
      name: "Unimoni Student Star",
      profession: "University of Melbourne",
      rating: "20,00,000",
      reviews: 423,
      tags: ["Illustrator", "Photoshop", "InDesign"],
      skill: "University of Melbourne",
      price: 20000,
      location: "Post Graduate",
      level: "lavel-1",
      language: "English",
      sort: "recommended",
      title: "I will create amazing designs as a Graphic Designer - Illustrators",
    },
    {
      id: 3,
      img: "/images/team/fl-3.png",
      name: "Young Women Awards ",
      profession: "Cranfield University",
      rating: "5,00,000",
      reviews: 312,
      tags: ["HTML", "CSS", "JavaScript"],
      skill: "Cranfield University",
      price: 30000,
      location: "Doctorate",
      level: "lavel-2",
      language: "Italian",
      sort: "new-arrivals",
      title: "I will develop web solutions as a Web Developer - Web Developers",
    },
  ];


  export const Destinationfreelancer = [
    {
      id: 1,
      img: "/images/team/fl-1.png",
      name: "Cost of living calculator",
      profession: "Nursing Assistant",
      rating: "10,00,000",
      reviews: 595,
      tags: ["Figma", "HTML5", "Sketch"],
      skill: "Curtin University",
      price: 10000,
      location: "Use this tool to estimate how much it could cost to have the lifestyle you want in Australia",
      level: "new",
      language: "Turkish",
      sort: "best-seller",
      title: "I will be your Nursing Assistant - UX Designer",
    },
    {
      id: 2,
      img: "/images/team/fl-2.png",
      name: "Locations in Australia",
      profession: "University of Melbourne",
      rating: "20,00,000",
      reviews: 423,
      tags: ["Illustrator", "Photoshop", "InDesign"],
      skill: "University of Melbourne",
      price: 20000,
      location: "Use this tool to estimate how much it could cost to have the lifestyle you want in Australia",
      level: "lavel-1",
      language: "English",
      sort: "recommended",
      title: "I will create amazing designs as a Graphic Designer - Illustrators",
    },
    {
      id: 3,
      img: "/images/team/fl-3.png",
      name: "Pre Departure Checklist",
      profession: "Cranfield University",
      rating: "5,00,000",
      reviews: 312,
      tags: ["HTML", "CSS", "JavaScript"],
      skill: "Cranfield University",
      price: 30000,
      location: "Use this tool to estimate how much it could cost to have the lifestyle you want in Australia",
      level: "lavel-2",
      language: "Italian",
      sort: "new-arrivals",
      title: "I will develop web solutions as a Web Developer - Web Developers",
    },
  ];