export const Scholarshipfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Fulbright Scholarship",
    profession: "International Relations",
    rating: "$30,000",
    reviews: 820,
    tags: ["Research", "International Affairs", "Policy"],
    skill: "Harvard University",
    price: 12000,
    location: "Post Graduate",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will assist with international policy research - Scholar",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Gates Cambridge Scholarship",
    profession: "Data Science",
    rating: "$25,000",
    reviews: 450,
    tags: ["Machine Learning", "AI", "Data Analytics"],
    skill: "Stanford University",
    price: 18000,
    location: "Under Graduate",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide data analysis and AI solutions - Data Scientist",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Rhodes Scholarship",
    profession: "Law and Governance",
    rating: "$50,000",
    reviews: 320,
    tags: ["Legal Studies", "Constitutional Law", "Governance"],
    skill: "Yale University",
    price: 25000,
    location: "Doctorate",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will assist with legal studies and governance research - Legal Advisor",
  },
];

export const ScholarshipUKfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Marshall Scholarship",
    profession: "Environmental Science",
    rating: "$35,000",
    reviews: 610,
    tags: ["Sustainability", "Climate Change", "Policy"],
    skill: "Princeton University",
    price: 15000,
    location: "Post Graduate",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will consult on environmental sustainability - Environmental Scientist",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Knight-Hennessy Scholars",
    profession: "Business Administration",
    rating: "$40,000",
    reviews: 500,
    tags: ["Leadership", "Management", "Strategy"],
    skill: "MIT",
    price: 20000,
    location: "Post Graduate",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide business management consulting - MBA Professional",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Schwarzman Scholars",
    profession: "Public Policy",
    rating: "$45,000",
    reviews: 410,
    tags: ["Public Policy", "Leadership", "Global Affairs"],
    skill: "Columbia University",
    price: 22000,
    location: "Doctorate",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will provide expertise on public policy and governance - Public Policy Expert",
  },
];

export const Destinationfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Cost of Living Calculator",
    profession: "Financial Analyst",
    rating: "$70,000",
    reviews: 590,
    tags: ["Economics", "Finance", "Cost of Living"],
    skill: "Harvard Business School",
    price: 20000,
    location: "Use this tool to estimate how much it could cost to live in the USA",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will calculate living costs and financial planning for USA cities - Financial Analyst",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Best Cities to Live in USA",
    profession: "Urban Planner",
    rating: "$60,000",
    reviews: 480,
    tags: ["Urban Development", "Infrastructure", "Sustainability"],
    skill: "UC Berkeley",
    price: 17000,
    location: "Explore the best cities to live in based on quality of life and cost",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide consultancy on urban living and city planning - Urban Planner",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Pre-Departure Checklist for USA",
    profession: "Travel Consultant",
    rating: "$50,000",
    reviews: 320,
    tags: ["Travel", "Visa", "Immigration"],
    skill: "New York University",
    price: 15000,
    location: "Essential tips before moving to the USA",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will assist with travel planning and visa preparation - Travel Consultant",
  },
];
