export const Scholarshipfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "DAAD Scholarships for International Students",
    profession: "Research and Innovation",
    rating: "€28,000",
    reviews: 820,
    tags: ["Research", "Innovation", "Higher Education"],
    skill: "Technical University of Munich",
    price: 12000,
    location: "Post Graduate",
    level: "new",
    language: "German, English",
    sort: "best-seller",
    title: "I will assist with research proposals and innovation projects - Scholar",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Heidelberg University Scholarships",
    profession: "Engineering and Technology",
    rating: "€24,000",
    reviews: 450,
    tags: ["Engineering", "Technology", "Innovation"],
    skill: "Heidelberg University",
    price: 18000,
    location: "Undergraduate",
    level: "level-1",
    language: "German, English",
    sort: "recommended",
    title: "I will provide engineering consultancy and tech solutions - Engineer",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Global Scholarships at Freie Universität Berlin",
    profession: "Business and Economics",
    rating: "€30,000",
    reviews: 320,
    tags: ["Business Studies", "Economics", "Global Strategy"],
    skill: "Freie Universität Berlin",
    price: 25000,
    location: "Doctorate",
    level: "level-2",
    language: "German, English",
    sort: "new-arrivals",
    title: "I will assist with business strategy and economic analysis - Economist",
  },
];

export const ScholarshipUKfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "RWTH Aachen University Scholarships",
    profession: "Environmental Science",
    rating: "€32,000",
    reviews: 610,
    tags: ["Environmental Studies", "Climate Change", "Sustainability"],
    skill: "RWTH Aachen University",
    price: 15000,
    location: "Post Graduate",
    level: "new",
    language: "German, English",
    sort: "best-seller",
    title: "I will consult on environmental sustainability and climate policy - Environmental Scientist",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "University of Mannheim Merit Scholarships",
    profession: "Business Administration",
    rating: "€38,000",
    reviews: 500,
    tags: ["Leadership", "Strategy", "Management"],
    skill: "University of Mannheim",
    price: 20000,
    location: "Post Graduate",
    level: "level-1",
    language: "German, English",
    sort: "recommended",
    title: "I will provide business management and leadership consulting - MBA Professional",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "TU Munich International Scholarships",
    profession: "Public Policy",
    rating: "€42,000",
    reviews: 410,
    tags: ["Public Policy", "Governance", "International Relations"],
    skill: "Technical University of Munich",
    price: 22000,
    location: "Doctorate",
    level: "level-2",
    language: "German, English",
    sort: "new-arrivals",
    title: "I will provide expertise on public policy and international relations - Public Policy Expert",
  },
];

export const Destinationfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Cost of Living Calculator for Germany",
    profession: "Financial Analyst",
    rating: "€55,000",
    reviews: 590,
    tags: ["Finance", "Economics", "Cost of Living"],
    skill: "University of Mannheim",
    price: 20000,
    location: "Use this tool to estimate living costs in Germany",
    level: "new",
    language: "German, English",
    sort: "best-seller",
    title: "I will calculate living costs and financial planning for German cities - Financial Analyst",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Best Cities to Live in Germany",
    profession: "Urban Planner",
    rating: "€50,000",
    reviews: 480,
    tags: ["Urban Planning", "Sustainability", "City Development"],
    skill: "Technical University of Berlin",
    price: 17000,
    location: "Explore the best cities to live in based on quality of life and cost",
    level: "level-1",
    language: "German, English",
    sort: "recommended",
    title: "I will provide consultancy on urban living and city planning in Germany - Urban Planner",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Pre-Departure Checklist for Germany",
    profession: "Travel Consultant",
    rating: "€45,000",
    reviews: 320,
    tags: ["Travel", "Visa", "Immigration"],
    skill: "Düsseldorf University of Applied Sciences",
    price: 15000,
    location: "Essential tips before moving to Germany",
    level: "level-2",
    language: "German, English",
    sort: "new-arrivals",
    title: "I will assist with travel planning and visa preparation for Germany - Travel Consultant",
  },
];
