export const LandingText = [
    {
      id: 1,
      icon: "flaticon-developer",
      skill: 1.853,
      title: "University Selection",
      brif: "We provide guidance on selecting universities or colleges based on the student's academic profile, budget, and preferences.e",
      img: "/images/listings/category-1.jpg",
    },
    {
      id: 2,
      icon: "flaticon-web-design-1",
      skill: 1.853,
      title: "Admission Assistance ",
      brif: "Our counselors assist students in preparing application materials and ensuring they meet admission requirements.",
      img: "/images/listings/category-2.jpg",
    },
    {
      id: 3,
      icon: "flaticon-digital-marketing",
      skill: 1.853,
      title: "Test Preparation",
      brif: "We may offer resources and coaching for standardized tests required for admission, such as the TOEFL, IELTS, GRE or GMAT.",
      img: "/images/listings/category-3.jpg",
    },
    {
      id: 4,
      icon: "flaticon-translator",
      skill: 1.853,
      title: "Visa and Immigration Support",
      brif: "Our counselors guide students through the visa application process, ensuring they have all necessary documents and understand immigration regulations.",
      img: "/images/listings/category-4.jpg",
    },
    {
      id: 5,
      icon: "flaticon-microphone",
      skill: 1.853,
      title: "Pre-departure Orientation",
      brif: "Our counsellors offer guidance on practical aspects of living and studying abroad, such as accommodation, healthcare, cultural differences, and safety.",
      img: "/images/listings/category-5.jpg",
    },
    {
      id: 6,
      icon: "flaticon-video-file",
      skill: 1.853,
      title: "Post-arrival Support",
      brif: "Our consultancy services offer assistance to students even after they arrive in their study destination, helping them settle in and addressing any issues they encounter.",
      img: "/images/listings/category-1.jpg",
    },
    {
      id: 7,
      icon: "flaticon-ruler",
      skill: 1.853,
      title: "Engineering & Architecture",
      brif: "Software Engineer, Web / Mobile Developer & More",
      img: "/images/listings/category-2.jpg",
    },
    {
      id: 8,
      icon: "flaticon-goal",
      skill: 1.853,
      title: "Finance & Accounting",
      brif: "Software Engineer, Web / Mobile Developer & More",
      img: "/images/listings/category-3.jpg",
    },
    {
      id: 9,
      icon: "flaticon-developer",
      skill: 1.853,
      title: "Development & IT",
      brif: "Software Engineer, Web / Mobile Developer & More",
      img: "/images/listings/category-1.jpg",
    },
    {
      id: 10,
      icon: "flaticon-web-design-1",
      skill: 1.853,
      title: "Design & Creative",
      brif: "Software Engineer, Web / Mobile Developer & More",
      img: "/images/listings/category-2.jpg",
    },
    {
      id: 11,
      icon: "flaticon-developer",
      skill: 1.853,
      title: "Development & IT",
      brif: "Software Engineer, Web / Mobile Developer & More",
      img: "/images/listings/category-1.jpg",
    },
    {
      id: 12,
      icon: "flaticon-web-design-1",
      skill: 1.853,
      title: "Design & Creative",
      brif: "Software Engineer, Web / Mobile Developer & More",
      img: "/images/listings/category-2.jpg",
    },
  ];
  