export const Scholarshipfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Government of Ireland Postgraduate Scholarship",
    profession: "Research and Innovation",
    rating: "€28,000",
    reviews: 820,
    tags: ["Research", "Innovation", "Higher Education"],
    skill: "Trinity College Dublin",
    price: 12000,
    location: "Post Graduate",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will assist with research proposals and innovation projects - Scholar",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Trinity College Dublin Scholarships",
    profession: "Engineering and Technology",
    rating: "€24,000",
    reviews: 450,
    tags: ["Engineering", "Technology", "Innovation"],
    skill: "Trinity College Dublin",
    price: 18000,
    location: "Undergraduate",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide engineering consultancy and tech solutions - Engineer",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "University College Dublin Global Excellence Scholarship",
    profession: "Business and Economics",
    rating: "€30,000",
    reviews: 320,
    tags: ["Business Studies", "Economics", "Global Strategy"],
    skill: "University College Dublin",
    price: 25000,
    location: "Doctorate",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will assist with business strategy and economic analysis - Economist",
  },
];

export const ScholarshipUKfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "University of Limerick Scholarships",
    profession: "Environmental Science",
    rating: "€32,000",
    reviews: 610,
    tags: ["Environmental Studies", "Climate Change", "Sustainability"],
    skill: "University of Limerick",
    price: 15000,
    location: "Post Graduate",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will consult on environmental sustainability and climate policy - Environmental Scientist",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Dublin City University Merit Scholarships",
    profession: "Business Administration",
    rating: "€38,000",
    reviews: 500,
    tags: ["Leadership", "Strategy", "Management"],
    skill: "Dublin City University",
    price: 20000,
    location: "Post Graduate",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide business management and leadership consulting - MBA Professional",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Maynooth University International Scholarships",
    profession: "Public Policy",
    rating: "€42,000",
    reviews: 410,
    tags: ["Public Policy", "Governance", "International Relations"],
    skill: "Maynooth University",
    price: 22000,
    location: "Doctorate",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will provide expertise on public policy and international relations - Public Policy Expert",
  },
];

export const Destinationfreelancer = [
  {
    id: 1,
    img: "/images/team/fl-1.png",
    name: "Cost of Living Calculator for Ireland",
    profession: "Financial Analyst",
    rating: "€55,000",
    reviews: 590,
    tags: ["Finance", "Economics", "Cost of Living"],
    skill: "University College Cork",
    price: 20000,
    location: "Use this tool to estimate living costs in Ireland",
    level: "new",
    language: "English",
    sort: "best-seller",
    title: "I will calculate living costs and financial planning for Irish cities - Financial Analyst",
  },
  {
    id: 2,
    img: "/images/team/fl-2.png",
    name: "Best Cities to Live in Ireland",
    profession: "Urban Planner",
    rating: "€50,000",
    reviews: 480,
    tags: ["Urban Planning", "Sustainability", "City Development"],
    skill: "University of Galway",
    price: 17000,
    location: "Explore the best cities to live in based on quality of life and cost",
    level: "level-1",
    language: "English",
    sort: "recommended",
    title: "I will provide consultancy on urban living and city planning in Ireland - Urban Planner",
  },
  {
    id: 3,
    img: "/images/team/fl-3.png",
    name: "Pre-Departure Checklist for Ireland",
    profession: "Travel Consultant",
    rating: "€45,000",
    reviews: 320,
    tags: ["Travel", "Visa", "Immigration"],
    skill: "Dublin Institute of Technology",
    price: 15000,
    location: "Essential tips before moving to Ireland",
    level: "level-2",
    language: "English",
    sort: "new-arrivals",
    title: "I will assist with travel planning and visa preparation for Ireland - Travel Consultant",
  },
];
